all:
	mvn install -DskipTests
	clear
	java -jar -ea target/EternityEditor-1.6-SNAPSHOT.jar
clean:
	mvn clean
	clear
rebuild:
	mvn clean install -DskipTests
run:
	java -jar -ea target/EternityEditor-1.6-SNAPSHOT.jar
